# Generated by Django 4.1 on 2022-08-23 16:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cstebase", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="question",
            name="title",
            field=models.CharField(max_length=10000, unique=True),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment",
                        to="cstebase.question",
                    ),
                ),
            ],
        ),
    ]
