# Generated by Django 4.1 on 2022-08-24 05:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cstebase", "0003_question_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="question",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
