# Generated by Django 4.1 on 2022-08-24 14:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cstebase", "0004_alter_comment_content_alter_question_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
