# Generated by Django 4.1 on 2022-08-26 16:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cstebase", "0006_alter_comment_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answered",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="question",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
