# Generated by Django 4.1 on 2022-08-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cstebase", "0007_question_answered_alter_comment_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="answered",
        ),
        migrations.AddField(
            model_name="comment",
            name="answered",
            field=models.BooleanField(default=False),
        ),
    ]
