# Generated by Django 4.1 on 2022-09-15 10:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cstebase", "0008_remove_question_answered_comment_answered"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("descriptions", ckeditor.fields.RichTextField()),
                ("image", models.ImageField(upload_to="about/")),
            ],
            options={
                "verbose_name": "About",
                "verbose_name_plural": "Abouts",
            },
        ),
        migrations.CreateModel(
            name="teamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("about", ckeditor.fields.RichTextField()),
                ("image", models.ImageField(upload_to="teamMember/")),
            ],
        ),
    ]
