# Generated by Django 4.1 on 2022-09-15 12:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cstebase", "0009_about_teammember"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={},
        ),
        migrations.RemoveField(
            model_name="about",
            name="descriptions",
        ),
        migrations.AddField(
            model_name="about",
            name="about",
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="about",
            name="name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
