# Generated by Django 4.1 on 2022-09-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cstebase", "0010_alter_about_options_remove_about_descriptions_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="About",
            new_name="AboutPage",
        ),
    ]
