# Generated by Django 4.1 on 2022-08-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("csteusers", "0002_profile_birthday_profile_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="username",
        ),
    ]
